### ISSUE TITLE
Defining the XX-500 in Q4

### ISSUE THREAD

**Issue by rokeya2023** [HUD-Data-Lab/DataLab#17]
Hi Gwen, I have a question regarding the part where we are defining the CoC XX-500 location. In Q4, when we are defining the CoC  XX-500, which is P1, and P2 only considering the Coc XX-500. I couldn’t find in the code how we are defining that we are only considering P2 including XX-500 and ignoring XX-601. May be the programming specification should have more explanation.
Please see the screenshot for line # 28 in R Studio and screenshot for Programming specification in page 6, number 4 the second bullet. I might be wrong.
Please see the code below:
![image](https://user-images.githubusercontent.com/120743917/209874279-3c08635d-1f32-4bcb-bff7-cf4d3a0859e4.png)
![image](https://user-images.githubusercontent.com/120743917/209874330-fe3f9a68-c72d-40d8-b3ce-5dca0dffeffc.png)
I might be wrong. Just for clarification.
Thanks!
Rokeya

**Comment by HUD-Data-Lab** [comment]
Hey Rokeya,

Great question. I think your question is answered in the below--let me know if you still think something is missing here!

On lines 34 and 35, we're checking each project to see whether it serves more than one CoC, and if so, whether any of the CoCs it serves match the CoC we're reporting on (`relevant_CoC` is set in the `DataLab_hc_variables.R` script).
```
31    multi_CoC_projects <- ProjectCoC %>%
32      mutate(relevant_to_CoC = relevant_CoC == CoCCode) %>%
33      group_by(ProjectID) %>%
34      summarise(num_of_CoCs = uniqueN(CoCCode),
35                relevant_to_CoC = max(relevant_to_CoC)) %>%
36      ungroup()
```
In the next chunk, we're assigning a CoC code to each individual enrollment to use for filtering. We start by joining the table we made above, then for each enrollment we check to see whether it's in a project that only serves the CoC we're reporting on. If so, we assign the report CoC to this enrollment in line 43. If it's in a project that serves multiple CoCs, it keeps the CoC code originally entered by the end user. If the enrollment is in a single-CoC project that does not serve the report CoC, this field is null.
```
39    enrollment_coc_plus <- EnrollmentCoC %>%
40      left_join(multi_CoC_projects, by = "ProjectID") %>%
41      # confirmed by Fran 12.21.22, issue #2
42      mutate(filter_CoC_code = case_when(
43        relevant_to_CoC & num_of_CoCs == 1 ~ relevant_CoC,
44        num_of_CoCs > 1 ~ CoCCode))
```
This lets us filter CE records by that `filter_CoC_code` while minimizing the clients excluded due to data entry errors. You'll see that filter applied to assessments on line 63 and to events on line 79.

**Comment by rokeya2023** [comment]
Thank you for taking the time for clarifying the matter. It is much better now.
