### ISSUE TITLE
add_client_info() formula issue

### ISSUE THREAD

**Issue by jessedirkman-ica** [HUD-Data-Lab/DataLab#5]
Possible bug in add_client_info() formula, from datalab_functions.R row 1088.

This function results in duplicate rows for any clients with multiple date_for_age values.  Because resultant table does not include HouseholdID or EnrollmentID columns, I'd recommend either a) altering table to contain only one row per PersonalID or b) add references to HouseholdID or EnrollmentID to use elsewhere in formulas.

**Comment by HUD-Data-Lab** [comment]
Ooh, good catch. Addressed this two ways--we now do additional filtering of enrollments prior to running the `add_client_info()` formula in the CE APR, and also added logic to keep just the most recent entry date of enrollments that may be relevant when calculating birthdate, per page 8 of the specs. This wasn't an issue in the CoC APR & CAPER because the enrollment filtering happens before this is called, so no need to revisit prior use of this.

Fixed with ab0c161d5a7688f8bc6169e7698b0d9cabd146de
