### ISSUE TITLE
Table 7a should display proper title in the Programming spec

### ISSUE THREAD

**Issue by rokeya2023** [HUD-Data-Lab/DataLab#6]
In the R studio line # 160, the code mutating Client_ Group and Total. Where Total is a Numeric variable and Client_ Group is a Character variable. In my understanding we are trying to add a new variable Client group in the table and trying to generate 6 groups Client_Group, Total, Without Children, With Children and Adults, With Only Children, Unknown Household Type. The report table should have a clear display for the title.
Screenshot for R studio:
![image](https://user-images.githubusercontent.com/120743917/208767493-72ad59d2-2345-4825-8ba0-f8adbe761b67.png)
The Report in Specification should display clearly
The first Column Under A should display Client Group
![image](https://user-images.githubusercontent.com/120743917/208767744-9dd8b2d8-eeb5-4551-aaaa-8b9d07f16879.png)

**Comment by HUD-Data-Lab** [comment]
Discussed in stand-up, this is all good--the line quoted here is just creating the total row. Normally we'd do this in-line with `adorn_totals("row")`, so this looks different, but in this case it is created separately because row 7 uses it for percentages. Row 7 won't have any data in the CE APR, but we're doing it this way for the sake of consistency with the CoC APR.
