### ISSUE TITLE
How to Handle Assessments for non-HoH clients?

### ISSUE THREAD

**Issue by jessedirkman-ica** [HUD-Data-Lab/DataLab#9]
Ambiguity/possible room for error regarding Assessments for non-HoH clients.

The Data Standards require Assessments for Heads of Household, and the code appears to assume that an assessment will be recorded if and only if (iff) a client is the head of household.

I'm not sure we'll get accurate results in all cases where assessments are recorded for non-heads of household (either in addition to or instead of an assessment for the current HoH.)

This came up for me in reviewing the code for 9a, but it may be relevant to more areas of the report.

**Comment by jessedirkman-ica** [comment]
Also on the topic of Heads of Households:

I think the specs "say" that we count each HoH once, and if that HoH was HoH for more than one enrollment, just count the HH at their most recent assessment.  This seems like a place where the specs could be clearer, though.

**Comment by jessedirkman-ica** [comment]
Item 3: Per the data standards, Relationship to Head of Household is answered once, at program start. Standards don't really specify what to do if the HoH leaves:  Do we just change the data at enrollment and pretend the other person was HoH all along? Some additional clarification on this would be awesome.

**Comment by ZachEhmannICA** [comment]
RE: Item 3 -- Found some clarification, but also a snag in that clarification:

Per the Data Dictionary (element 3.15), HUD requires systems to be able to assign a new HoH if the original leaves, but this needs to be made effective for the entire enrollment. You may already see the issue: if the client assigned entered _after_ the original HoH, there's a portion of the enrollment where it now appears there is no HoH.

**Comment by ZachEhmannICA** [comment]
I also wanted to note that this issue impacts enrollment_recent_assessment in CE_APR.R:

Here's the current code:
`enrollment_recent_assessment <- enrollment_data %>%
  inner_join(most_recent_assessment %>%
               select(HouseholdID, AssessmentDate, AssessmentType,
                      PrioritizationStatus) %>%
               group_by(HouseholdID) %>%
               arrange(desc(AssessmentDate)) %>%
               slice(1L) %>%
               ungroup(),
             by = "HouseholdID") %>%
  filter(AssessmentDate >= EntryDate &
           (AssessmentDate <= ExitDate |
              is.na(ExitDate)))`

The most_recent_assessment df holds the most recently dated assessment for each _Client_. So in a case where a client is a HH member in two sequential enrollments -- "A" and "B" -- but is only the HoH in "B," the result is that enrollment_recent_assessment retains **only** enrollment "B," even though a different HoH was assessed for enrollment "A," and the HH composition may be different.

**Comment by HUD-Data-Lab** [comment]
> Also on the topic of Heads of Households:
> 
> I think the specs "say" that we count each HoH once, and if that HoH was HoH for more than one enrollment, just count the HH at their most recent assessment. This seems like a place where the specs could be clearer, though.

This is correct--it's addressed more clearly on page 18 of the reporting glossary, which is referenced but not quoted in the CE APR specs
> **Unduplicated Household Counts**
> Unduplicated household counts should be determined by performing a distinct count of [personal IDs] of all heads
of households (people who have [relationship to head of household] = Self) in the report range.
In the event that your system identifies people in the date range with no head of household, a flag to the system
user may be in order, i.e. the head of household may have left the household and a new head of household may not
have been assigned.

**Comment by HUD-Data-Lab** [comment]
> I also wanted to note that this issue impacts enrollment_recent_assessment in CE_APR.R:
> 
> Here's the current code: `enrollment_recent_assessment <- enrollment_data %>% inner_join(most_recent_assessment %>% select(HouseholdID, AssessmentDate, AssessmentType, PrioritizationStatus) %>% group_by(HouseholdID) %>% arrange(desc(AssessmentDate)) %>% slice(1L) %>% ungroup(), by = "HouseholdID") %>% filter(AssessmentDate >= EntryDate & (AssessmentDate <= ExitDate | is.na(ExitDate)))`
> 
> The most_recent_assessment df holds the most recently dated assessment for each _Client_. So in a case where a client is a HH member in two sequential enrollments -- "A" and "B" -- but is only the HoH in "B," the result is that enrollment_recent_assessment retains **only** enrollment "B," even though a different HoH was assessed for enrollment "A" _and_ the HH composition may differ between enrollments.

In this case, would the assessment for the other household member be attached to enrollment A (assuming they haven't also been reassessed in another program since that point? Want to be sure we're on the same page here.

**Comment by HUD-Data-Lab** [comment]
Received guidance to help with this question:

### Question
Assessments should be attached to the head of household, but enrollments/relationships are fluid and there are valid reasons this would not be the case. The specs seem to expect assessments to always be attached to the head of household, can we instead use the most recent assessment in the household? This is technically allowable as the specs are written because they reference people with assessments rather than heads of household with assessments, but we will want to rephrase in the next release for the sake of clarity.
### Guidance
Identify the most recent assessment in the report for each individual. For each household, look at the assessment dates identified above. If there are multiple assessed household members, use the most recent assessment. The head of household is counted where appropriate based on that date, regardless of whether they were the assessed individual.

**Comment by ZachEhmannICA** [comment]
> > I also wanted to note that this issue impacts enrollment_recent_assessment in CE_APR.R:
> > Here's the current code: `enrollment_recent_assessment <- enrollment_data %>% inner_join(most_recent_assessment %>% select(HouseholdID, AssessmentDate, AssessmentType, PrioritizationStatus) %>% group_by(HouseholdID) %>% arrange(desc(AssessmentDate)) %>% slice(1L) %>% ungroup(), by = "HouseholdID") %>% filter(AssessmentDate >= EntryDate & (AssessmentDate <= ExitDate | is.na(ExitDate)))`
> > The most_recent_assessment df holds the most recently dated assessment for each _Client_. So in a case where a client is a HH member in two sequential enrollments -- "A" and "B" -- but is only the HoH in "B," the result is that enrollment_recent_assessment retains **only** enrollment "B," even though a different HoH was assessed for enrollment "A" _and_ the HH composition may differ between enrollments.
> 
> In this case, would the assessment for the other household member be attached to enrollment A (assuming they haven't also been reassessed in another program since that point? Want to be sure we're on the same page here.

Yup! To clarify, let's say there are two clients in both enrollment cases. Client 1 is HoH in "A"; Client 2 is HoH in "B". Because the enrollment "B" assessment happened later and Client 2 was in both enrollments, only enrollment "B" is retained, and we ignore enrollment "A" and the associated assessment that happened for Client 1.

So in this case, it's not that non-HoH members are assessed, just that the HoH changes for a group of clients between enrollments. I think functionally this means that we're kind of setting a "most recent household configuration" based on the last-assessed HoH [or client, given the recent guidance] for groups of clients that appear together multiple times in the reporting timeframe. If there was an enrollment "C" that only had Client 2, Client 1 would be excluded entirely from Q4-9 counts.

Still thinking through this, so there may also just be something I'm missing/misunderstanding that clarifies this isn't an issue!

**Comment by ZachEhmannICA** [comment]
During meeting, Gwen clarified that the %>% group_by(HouseholdID) %>% step in the chunk preserves household-level detail, keeping the most recent assessment information enrollment case. In the example, my understanding is that we'd have a household count of 2, even if household composition did not change, but the client count would not be duplicated (2 instead of 4).
